on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

name: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy LICENSE file
        run: cp -p LICENSE mmd_tools/

      - name: Remove typings for development
        run: rm -rf mmd_tools/typings

      - name: Create a zip
        run: (cd mmd_tools && find . -type f ! -path "*/.*" ! -path "*/__pycache__/*" -print | zip -9r "../mmd_tools-${GITHUB_REF_NAME}.zip" -@)

      - name: Create a Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            mmd_tools-${{ github.ref_name }}.zip
          draft: true
          generate_release_notes: true
          prerelease: false
