on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

name: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate zip filename
        run: |
          declare -A tag_prefix_to_blender_version=(
            ["v2"]="bl3.6"
            ["v4"]="bl4.2"
          )
          echo "zip_filename=mmd_tools-${GITHUB_REF_NAME}-${tag_prefix_to_blender_version[${GITHUB_REF_NAME%%.*}]}.zip" >> $GITHUB_ENV

      - name: Copy LICENSE file
        run: cp -p LICENSE mmd_tools/

      - name: Remove development-only files
        run: rm -rf mmd_tools/typings

      - name: Create a zip
        run: |
          (
            cd mmd_tools &&
            find . -type f ! -path "*/.*" ! -path "*/__pycache__/*" -print |
            zip -9r "../${{ env.zip_filename }}" -@
          )

      - name: Create a Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: ${{ env.zip_filename }}
          draft: true
          generate_release_notes: true
          prerelease: false
